title: Rahammetoela Toekiman also known as Tobiyo “Fuseteam” Kuujikai, xiaofuse, feishikong, Merkhad Luigton
#Jekyll configuration
livereload: true
host: 0.0.0.0
#theme: jekyll-theme-cayman
remote_theme: feishikong/meet-the-theme
favicon: assets/images/favicon.png
markdown: kramdown
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag # add this line to the plugins list if you already have one
